### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by hykelauncher** [gsusI/Telegram-Group-or-Channel-users-to-CSV#8]
Option 2 and 3 not working, please help

Traceback (most recent call last):
  File "main.py", line 188, in <module>
    add_users_to_group()
  File "main.py", line 25, in add_users_to_group
    input_file = sys.argv[1]
IndexError: list index out of range
termuxblack >

**Comment by Itay602** [comment]
not workink for me too
can you help??

**Comment by Urhengulas** [comment]
`sys.argv[1]` tries to get the first argument (the input file), but apparently it does not exist. You need to invoke it like `python telethon-bot-add-users-to-groups.py members-file.csv`.
